name: DeepSeek Translator
description: GitHub Action to translate i18next JSON using DeepSeek API.
author: theJian

inputs:
  deepseek-api-key:
    description: API key for DeepSeek
    required: true

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Run DeepSeek Translator
      shell: bash
      env:
        DEEPSEEK_API_KEY: ${{ inputs.deepseek-api-key }}
      run: |
        uvx --from git+https://github.com/theJian/deepseek-translator@main deepseek-translator
