[project]
name = "deepseek-translator"
version = "0.1.0"
description = "AI-powered translation tool using DeepSeek API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.91.0",
    "python-dotenv>=1.1.1",
]
